name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use Node.js ${{ matrix.node-version }}
      run: |
        echo "pwd"
        npm i
        cd frontend
        npm i
        npm run build
